//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loader_fra.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("loader_fra.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bqKbeAWZnkpWQ8zaF2dKsSqVpeYblfMq.
        /// </summary>
        internal static string name_e_key {
            get {
                return ResourceManager.GetString("name_e_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wIYyQ3yicgxpFBxEPP4FiM5lGwWb9NF8.
        /// </summary>
        internal static string owner_e_key {
            get {
                return ResourceManager.GetString("owner_e_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whDqUN3sDkq789Oo2Y6nzixHue9QDJVF.
        /// </summary>
        internal static string secret_e_key {
            get {
                return ResourceManager.GetString("secret_e_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0iUBJU0ASSjWQ4wRsNSU4aJxbIakSDoq.
        /// </summary>
        internal static string version_e_key {
            get {
                return ResourceManager.GetString("version_e_key", resourceCulture);
            }
        }
    }
}
